export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SETUP_BEGIN = 'SETUP_BEGIN';
export const SETUP_FAILURE = 'SETUP_FAILURE';

export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';

export const FETCH_CATEGORY_OPTIONS_SUCCESS = 'FETCH_CATEGORY_OPTIONS_SUCCESS';
export const FETCH_TRANSACTION_TYPES_SUCCESS = 'FETCH_TRANSACTION_TYPES_SUCCESS';

export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const SET_EDIT_TRANSACTION = 'SET_EDIT_TRANSACTION';
export const FETCH_TRANSACTION_STATS_SUCCESS = 'FETCH_TRANSACTION_STATS_SUCCESS';

export const HANDLE_TRANSACTION_INPUT = 'HANDLE_TRANSACTION_INPUT';
export const CLEAR_TRANSACTION_FORM_VALUES = 'CLEAR_TRANSACTION_FORM_VALUES';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const CLEAR_FILTERS = 'CLEAR_FILTERS';

export const CHANGE_PAGE = 'CHANGE_PAGE';
